import os
import sys
import geopandas as gpd
import pandas as pd
from plot_utils import *
    
def caribbean_sector_attributes():    
    sector_attributes = [
                            # {
                            #     "sector":"transport",
                            #     "sector_gpkg":"ports.gpkg",
                            #     "sector_label":"Ports",
                            #     "country_filter":'Yes',
                            #     "filter_column":"iso_code",
                            #     "label":"port_name",
                            #     "edges_layer":None,
                            #     "nodes_layer":None,
                            #     "areas_layer":"areas",
                            #     "edges_id_column":None,
                            #     "nodes_id_column":"node_id",
                            #     "areas_id_column":"node_id",
                            #     "edges_damage_filter_column":None,
                            #     "nodes_damage_filter_column":None,
                            #     "areas_damage_filter_column":None,
                            #     "edges_damage_categories":None,
                            #     "nodes_damage_categories":None,
                            #     "areas_damage_categories":None,
                            #     "edges_classify_column":None,
                            #     "nodes_classify_column":"asset_type",
                            #     "areas_classify_column":"asset_type",
                            #     "edges_categories":None,
                            #     "nodes_categories":None,
                            #     "areas_categories":["ports"],
                            #     "edges_categories_colors":None,
                            #     "nodes_categories_colors":None,
                            #     "areas_categories_colors":["#08306b"],
                            #     "edges_categories_labels":None,
                            #     "nodes_categories_labels":None,
                            #     "areas_categories_labels":["PORT AREAS"],
                            #     "edges_categories_linewidth":[2],
                            #     "areas_categories_linewidth":[2],
                            #     "edges_categories_zorder":None,
                            #     "nodes_categories_markersize":[15.0],
                            #     "nodes_categories_marker":["o"],
                            #     "nodes_categories_zorder":[11],
                            #     "areas_categories_zorder":[11],
                            #     "nodes_loss_result": "ports",
                            #     "edges_loss_result":None,
                            #     "nodes_loss_result":"ports",
                            #     "edges_loss_result":None
                            # },
                            # {
                            #     "sector":"transport",
                            #     "sector_gpkg":"airports.gpkg",
                            #     "sector_label":"Airports",
                            #     "country_filter":'Yes',
                            #     "filter_column":"iso_code",
                            #     "label":"name",
                            #     "edges_layer":None,
                            #     "nodes_layer":None,
                            #     "areas_layer":"areas",
                            #     "edges_id_column":None,
                            #     "nodes_id_column":None,
                            #     "areas_id_column":"node_id",
                            #     "edges_damage_filter_column":None,
                            #     "nodes_damage_filter_column":None,
                            #     "areas_damage_filter_column":None,
                            #     "edges_damage_categories":None,
                            #     "nodes_damage_categories":None,
                            #     "areas_damage_categories":None,
                            #     "edges_classify_column":None,
                            #     "nodes_classify_column":None,
                            #     "areas_classify_column":"asset_type",
                            #     "edges_categories":None,
                            #     "nodes_categories":None,
                            #     "areas_categories":["airports"],
                            #     "edges_categories_colors":None,
                            #     "nodes_categories_colors":None,
                            #     "areas_categories_colors":["#8c510a"],
                            #     "edges_categories_labels":None,
                            #     "nodes_categories_labels":None,
                            #     "areas_categories_labels":["AIRPORT AREAS"],
                            #     "edges_categories_linewidth":[2],
                            #     "areas_categories_linewidth":[2],
                            #     "edges_categories_zorder":None,
                            #     "nodes_categories_markersize":[15.0],
                            #     "areas_categories_markersize":[15.0],
                            #     "nodes_categories_marker":["o"],
                            #     "nodes_categories_zorder":[11],
                            #     "areas_categories_zorder":[11]
                            # },
                            # {
                            #     "sector":"transport",
                            #     "sector_gpkg":"roads.gpkg",
                            #     "sector_label":"Roads",
                            #     "country_filter":'No',
                            #     "filter_column":"iso_code",
                            #     "label":None,
                            #     "edges_layer":"edges",
                            #     "nodes_layer":None,
                            #     "areas_layer":None,
                            #     "edges_id_column":"edge_id",
                            #     "nodes_id_column":"node_id",
                            #     "areas_id_column":None,
                            #     "edges_classify_column":"highway",
                            #     "nodes_classify_column":None,
                            #     "areas_classify_column":None,
                            #     "edges_damage_filter_column":None,
                            #     "nodes_damage_filter_column":None,
                            #     "areas_damage_filter_column":None,
                            #     "edges_damage_categories":None,
                            #     "nodes_damage_categories":None,
                            #     "areas_damage_categories":None,
                            #     "edges_categories":["primary","secondary","tertiary","residential","other"],
                            #     "nodes_categories":None,
                            #     "areas_categories":None,
                            #     "edges_categories_colors":["#000000","#6a51a3","#ce1256","#f16913","#8c510a"],
                            #     "nodes_categories_colors":["#800026"],
                            #     "areas_categories_colors":None,
                            #     "edges_categories_labels":["Primary","Secondary","Tertiary","Residential","Other"],
                            #     "nodes_categories_labels":None,
                            #     "areas_categories_labels":None,
                            #     "edges_categories_linewidth":[1.0,1.0,1.0,1.0,0.5],
                            #     "areas_categories_linewidth":[1.0,1.0,1.0,1.0,0.5],
                            #     "edges_categories_zorder":[10,9,8,7,6],
                            #     "nodes_categories_markersize":[10.0],
                            #     "nodes_categories_marker":".",
                            #     "nodes_categories_zorder":[11],
                            #     "nodes_loss_result": "road_bridges",
                            #     "edges_loss_result":"road_rail_edges"
                            # },
                            # {
                            #     "sector":"energy",
                            #     "sector_gpkg":"energy.gpkg",
                            #     "sector_label":"Energy",
                            #     "country_filter":'No',
                            #     "filter_column":"iso_code",
                            #     "label":None,
                            #     "edges_layer":"edges",
                            #     "nodes_layer":"nodes",
                            #     "areas_layer":"areas",
                            #     "edges_id_column":"edge_id",
                            #     "nodes_id_column":"node_id",
                            #     "areas_id_column":"node_id",
                            #     "edges_classify_column":"asset_type",
                            #     "nodes_classify_column":"asset_type",
                            #     "areas_classify_column":"asset_type",
                            #     "edges_damage_filter_column":None,
                            #     "nodes_damage_filter_column":None,
                            #     "areas_damage_filter_column":None,
                            #     "edges_damage_categories":None,
                            #     "nodes_damage_categories":None,
                            #     "areas_damage_categories":None,
                            #     "edges_categories":["ohl","uc","dummy"],
                            #     "nodes_categories":["diesel","geothermal","hydro","solar",
                            #                     "substation","pole"],
                            #     "areas_categories":["diesel","geothermal","hydro","solar",
                            #                     "substation"],
                            #     "edges_categories_colors":["#000000","#006d2c","#66c2a4"],
                            #     "nodes_categories_colors":["#d73027","#1a9850","#4575b4","#fee08b",
                            #                                 "#4d4d4d","#a6bddb"],
                            #     "areas_categories_colors":["#d73027","#1a9850","#4575b4","#fee08b",
                            #                                 "#4d4d4d"],
                            #     "edges_categories_labels":["Overhead lines","Underground cables","Added lines"],
                            #     "nodes_categories_labels":["Diesel","Geothermal",
                            #                             "Hydropower","Solar",
                            #                             "Substation","Poles"
                            #                             ],
                            #     "areas_categories_labels":["Diesel","Geothermal",
                            #                             "Hydropower","Solar",
                            #                             "Substation"
                            #                             ],
                            #     "edges_categories_linewidth":[0.5,0.5,0.3],
                            #     "areas_categories_linewidth":[3,3,3,3,3],
                            #     "edges_categories_zorder":[11,9,8],
                            #     # "nodes_categories_markersize":[15.0,15.0,15.0,15.0,15.0,15.0,15.0],
                            #     # "nodes_categories_marker":["s","s","s","s","s","o","."],
                            #     # "nodes_categories_zorder":[15,15,15,15,15,14,13],
                            #     "nodes_categories_markersize":[10.0,10.0,10.0,10.0,10.0,3.0],
                            #     "nodes_categories_marker":["^","v","s","p","o","o"],
                            #     "nodes_categories_zorder":[15,15,15,15,14,10],
                            #     "areas_categories_zorder":[15,15,15,15,14],
                            #     "nodes_loss_result": "electricity_nodes",
                            #     "edges_loss_result":"electricity_edges"
                            # },
                            # {
                            #     "sector":"water",
                            #     "sector_gpkg":"wtp.gpkg", # We will integrate the NWC layers together for this
                            #     "sector_label":"Water Treatment",
                            #     "edges_layer":None,
                            #     "nodes_layer":"nodes",
                            #     "areas_layer":None,
                            #     "edges_id_column":None,
                            #     "nodes_id_column":"node_id",
                            #     "areas_id_column":None,
                            #     "edges_classify_column":None,
                            #     "nodes_classify_column":"asset_type",
                            #     "areas_classify_column":None,
                            #     "edges_damage_filter_column":None,
                            #     "nodes_damage_filter_column":None,
                            #     "areas_damage_filter_column":None,
                            #     "edges_damage_categories":None,
                            #     "nodes_damage_categories":None,
                            #     "areas_damage_categories":None,
                            #     "edges_categories":None,
                            #     "nodes_categories":["wtp"],
                            #     "areas_categories":None,
                            #     "edges_categories_colors":None,
                            #     "nodes_categories_colors":["#807dba",
                            #                                 ],
                            #     "areas_categories_colors":None,
                            #     "edges_categories_labels":None,
                            #     "nodes_categories_labels":["Water Treatment Plant"],
                            #     "areas_categories_labels":None,
                            #     "edges_categories_linewidth":[0.5],
                            #     "areas_categories_linewidth":[0.5],
                            #     "edges_categories_zorder":[10],
                            #     "nodes_categories_markersize":[6.0],
                            #     "nodes_categories_marker":["o"],
                            #     "nodes_categories_zorder":[15],
                            #     "areas_categories_zorder":[15],
                            #     "nodes_loss_result": "potable_facilities",
                            #     "edges_loss_result":"potable_pipelines"                           
                            # },
                            # {
                            #     "sector":"water",
                            #     "sector_gpkg":"wwtp.gpkg", # We will integrate the NWC layers together for this
                            #     "sector_label":"Wastewater Treatment",
                                
                            #     "edges_layer":None,
                            #     "nodes_layer":"nodes",
                            #     "areas_layer":None,
                                
                            #     "edges_id_column":None,
                            #     "nodes_id_column":"node_id",
                            #     "areas_id_column":None,
                            #     "edges_classify_column":"asset",
                            #     "nodes_classify_column":"asset_type",
                            #     "areas_classify_column":None,
                            #     "edges_damage_filter_column":None,
                            #     "nodes_damage_filter_column":None,
                            #     "areas_damage_filter_column":None,
                            #     "edges_damage_categories":None,
                            #     "nodes_damage_categories":None,
                            #     "areas_damage_categories":None,
                            #     "edges_categories":None,
                            #     "nodes_categories":["wwtp"],
                            #     "areas_categories":None,
                            #     "edges_categories_colors":None,
                            #     "nodes_categories_colors":[
                            #                                 "#6a51a3"
                            #                                 ],
                            #     "areas_categories_colors":None,
                                
                            #     "edges_categories_labels":None,
                            #     "nodes_categories_labels":["Wastewater Treatment Plant"],
                            #     "areas_categories_labels":None,
                            #     "edges_categories_linewidth":[0.5],
                            #     "areas_categories_linewidth":[0.5],
                            #     "edges_categories_zorder":[10],
                            #     "nodes_categories_markersize":[6.0],
                            #     "areas_categories_markersize":[6.0],
                            #     "nodes_categories_marker":["s"],
                            #     "edges_categories_zorder":[15],
                            #     "nodes_categories_zorder":[15],
                            #     "area_categories_zorder":[15],
                            #     "nodes_loss_result": "potable_facilities",
                            #     "edges_loss_result":"potable_pipelines"                           
                            # },
                            {
                                "sector":"social",
                                "sector_gpkg":"education.gpkg",
                                "sector_label":"Schools",
                                "country_filter":'Yes',
                                "filter_column":"iso_code",
                                "label":None,
                                "edges_layer":None,
                                "nodes_layer":None,
                                "areas_layer":"areas",
                                "edges_id_column":None,
                                "nodes_id_column":"node_id",
                                "areas_id_column":"node_id",
                                "edges_damage_filter_column":None,
                                "nodes_damage_filter_column":None,
                                "areas_damage_filter_column":None,
                                "edges_damage_categories":None,
                                "nodes_damage_categories":None,
                                "areas_damage_categories":None,
                                "edges_classify_column":None,
                                "nodes_classify_column":"asset_type",
                                "areas_classify_column":"asset_type",
                                "edges_categories":None,
                                "nodes_categories":None,
                                "areas_categories":["education"],
                                "edges_categories_colors":None,
                                "nodes_categories_colors":None,
                                "areas_categories_colors":["#3690c0"],
                                "edges_categories_labels":None,
                                "nodes_categories_labels":None,
                                "areas_categories_labels":["SCHOOL AREAS"],
                                "edges_categories_linewidth":[2],
                                "areas_categories_linewidth":[2],
                                "edges_categories_zorder":None,
                                "nodes_categories_markersize":[15.0],
                                "nodes_categories_marker":["o"],
                                "nodes_categories_zorder":[11],
                                "areas_categories_zorder":[11],
                                "nodes_loss_result": "education",
                                "edges_loss_result":None,
                                "nodes_loss_result":"education",
                                "edges_loss_result":None
                            },
                            {
                                "sector":"social",
                                "sector_gpkg":"health.gpkg",
                                "sector_label":"Hospitals",
                                "country_filter":'Yes',
                                "filter_column":"iso_code",
                                "label":None,
                                "edges_layer":None,
                                "nodes_layer":None,
                                "areas_layer":"areas",
                                "edges_id_column":None,
                                "nodes_id_column":"node_id",
                                "areas_id_column":"node_id",
                                "edges_damage_filter_column":None,
                                "nodes_damage_filter_column":None,
                                "areas_damage_filter_column":None,
                                "edges_damage_categories":None,
                                "nodes_damage_categories":None,
                                "areas_damage_categories":None,
                                "edges_classify_column":None,
                                "nodes_classify_column":"asset_type",
                                "areas_classify_column":"asset_type",
                                "edges_categories":None,
                                "nodes_categories":None,
                                "areas_categories":["health"],
                                "edges_categories_colors":None,
                                "nodes_categories_colors":None,
                                "areas_categories_colors":["#cc4c02"],
                                "edges_categories_labels":None,
                                "nodes_categories_labels":None,
                                "areas_categories_labels":["HEALTH FACILITY AREAS"],
                                "edges_categories_linewidth":[2],
                                "areas_categories_linewidth":[2],
                                "edges_categories_zorder":None,
                                "nodes_categories_markersize":[15.0],
                                "nodes_categories_marker":["o"],
                                "nodes_categories_zorder":[11],
                                "areas_categories_zorder":[11],
                                "nodes_loss_result": "health",
                                "edges_loss_result":None,
                                "nodes_loss_result":"health",
                                "edges_loss_result":None
                            },

                        ]

    return sector_attributes

def jamaica_port_and_airport_nodes():
    config = load_config()
    processed_data_path = config['paths']['data']


    transport_data_path = os.path.join(processed_data_path,
                        "networks",
                        "transport")
    ports = gpd.read_file(os.path.join(transport_data_path,"port_polygon.gpkg"),layer="areas").to_crs(epsg=JAMAICA_GRID_EPSG)
    ports["asset_type"] = "port"
    airports = gpd.read_file(os.path.join(transport_data_path,"airport_polygon.gpkg"),layer="areas").to_crs(epsg=JAMAICA_GRID_EPSG)
    airports["asset_type"] = "airport"
    nodes = pd.concat([ports[["nodes_id","name","asset_type","geometry"]],
                        airports[["nodes_id","name","asset_type","geometry"]]],
                        axis=0,ignore_index=True)
    
    nodes["centroid"] = nodes.geometry.centroid
    nodes.drop("geometry",axis=1,inplace=True)
    nodes.rename(columns={"centroid":"geometry"},inplace=True)
    nodes = gpd.GeoDataFrame(nodes,geometry="geometry",crs=f"EPSG:{JAMAICA_GRID_EPSG}")

    return nodes

def jamaica_port_nodes():
    config = load_config()
    processed_data_path = config['paths']['data']

    transport_data_path = os.path.join(processed_data_path,
                        "networks",
                        "transport")
    ports = gpd.read_file(os.path.join(transport_data_path,"port_polygon.gpkg"),layer="areas").to_crs(epsg=JAMAICA_GRID_EPSG)
    ports["asset_type"] = "port"
    ports["geometry"] = ports.apply(lambda x: x.geometry.centroid,axis=1)
    ports = gpd.GeoDataFrame(ports,geometry="geometry",crs=f"EPSG:{JAMAICA_GRID_EPSG}")

    return ports
